### ISSUE TITLE
system timeout in 120 second

### ISSUE THREAD

**Issue by chankitm** [vaughany/yourls-bulk-import-and-shorten#1]
Q:What you did?
A:upload a test.csv with 1000 rows of data for url shorten.
Q:What you expected to happen?
A:1000 url shortened over the stated csv file.
Q:What actually happened?
A: Got a timeout(120 seconds) error message, and found no updates in the stated file.
however, there are about 50 rows of data found shortened over the index page(http://XXX/yourls/admin/index.php)
Q:Steps to reproduce?
A:perform the "no keyword"  portion of the "USE" section, with a test.csv file with 1000 rows of data.

**Comment by vaughany** [comment]
Hi @chankitm. Sorry for the delay in responding to you, I've been on holiday.

If you are only seeing 50 imported URLs in 120 seconds, then it's taking more than 2 seconds to process each line in your CSV file, which is much, much too slow.  (PHP is most likely timing out: you can raise the time limit on script execution in your `php.ini` file, just search for `max_execution_time`, but this is only a patch, not a fix.)  At this speed it would take around 40 mins to process your CSV file and that's ludicrous!  Can you think of any reason at your end why this might be the case? Slow computer or server, or slow internet connection, for example. How big is your CSV file in Kb/Mb?

I'd quite like to see your CSV file and use it to test: is there any way you could get it to me? (My email address is on my profile, if you don't want to upload it.) 

Regards,

Vaughany.

**Comment by vaughany** [comment]
Unsure if the original reporter is still following this, but I've pushed an update that should significantly speed up the process, but at the cost of titles pulled from the supplied URL.
