### ISSUE TITLE
long url has comma so truncating on upload

### ISSUE THREAD

**Issue by geckogirl** [vaughany/yourls-bulk-import-and-shorten#2]
I have a CSV file with a long and short URL of the links I want to shorten.  This worked fine a while ago but today when I upload the file it sees a comma in the middle of the long url so truncates it at that point and then doesn't see my second column so auto-assigns short urls to each entry,  What has changed?

**Comment by geckogirl** [comment]
Got around it by using %2C in long url and then had to edit Excel CSV file to use commas to deliniate the columns instead of semi-colons.  Very odd that it should change but at least I have a working solution.  Would still be interested to know what/why it changed

**Comment by vaughany** [comment]
Ideally a CSV file's columns should be delineated with quotes, and I can only assume that this one wasn't, and the comma in the url was seen as separating fields.
