### ISSUE TITLE
Popular Click Extended Error

### ISSUE THREAD

**Issue by JF1313** [vaughany/yourls-bulk-import-and-shorten#5]
Paul, thanks for the update. I've installed Popular Clicks Extended. When I run the plug-in I receive the following error:

Fatal error: Uncaught Error: Call to undefined function vaughany_pce_this_period() in /home/jeffrey/public_html/user/plugins/popular-links-extended/plugin.php:321 Stack trace: #0 /home/jeffrey/public_html/includes/functions-plugins.php(596): vaughany_pce_display_page() #1 /home/jeffrey/public_html/admin/plugins.php(8): yourls_plugin_admin_page('vaughany_pce') #2 {main} thrown in /home/jeffrey/public_html/user/plugins/popular-links-extended/plugin.php on line 321

**Comment by vaughany** [comment]
Reported in the correct repo, here: https://github.com/vaughany/yourls-popular-clicks-extended/issues/10
